<template>
  <v-app id="inspire">
    <AppBar />
    <v-container style="height: 1000px;">
      <v-card>
        <v-img src="./../assets/psyk_logo.png" max-height="344px" class="grey darken-4"></v-img>
        <v-list-item-content style="padding:10px">
          <div class="overline mb-4">Qui sommes nous?</div>
          <p class="font-weight-light">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque lorem consectetur aliquam lobortis. Donec commodo vestibulum urna ac aliquam. In hac habitasse platea dictumst. Morbi velit libero, tempor id ante in, varius dapibus diam. Quisque nec arcu eros. Aliquam cursus nisi ex, blandit ultricies tortor luctus eget. Duis vulputate, dolor vitae ornare tincidunt, diam dui venenatis magna, in molestie urna nulla nec lorem. Donec libero ligula, elementum vel orci in, sodales finibus nisl. In elementum turpis at elit aliquam, egestas varius purus aliquam. Pellentesque ornare metus nec velit mattis mattis. In risus dui, ultrices sed neque convallis, tempor porttitor nulla. Nulla nec volutpat nulla, eget aliquam mauris.
            Proin non sollicitudin sem. In in lacus nisi. Nullam fringilla justo enim, vitae euismod tortor pretium et. Aliquam bibendum quis est vel porta. Quisque dignissim, nulla ut faucibus interdum, massa turpis ultrices ligula, quis cursus orci purus vehicula ipsum. Sed risus felis, sagittis a nunc sit amet, pellentesque pretium justo. Maecenas vitae urna tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin sed tortor vel mi condimentum ornare. Curabitur erat tortor, rhoncus non consectetur eu, blandit eu dolor. In erat sapien, malesuada at egestas sed, aliquam ut enim. Nam ut gravida ligula, id imperdiet erat.
            Integer cursus ipsum at neque sollicitudin viverra. Donec sed mi efficitur, imperdiet sapien ac, dictum eros. Sed ullamcorper augue in urna laoreet, congue ultrices nulla gravida. Morbi pellentesque semper fermentum. Ut venenatis lacus a arcu posuere, in gravida quam volutpat. Duis est ante, tempus sit amet felis eu, tempor pretium risus. Integer efficitur diam dui, non porttitor ex egestas a. Donec quis metus eu turpis commodo tincidunt. Pellentesque venenatis neque quis orci egestas, quis ullamcorper sapien suscipit. Suspendisse elementum, erat eget fermentum feugiat, purus urna interdum magna, ac rhoncus orci eros fermentum nisi. Integer sed lacus in ante scelerisque malesuada in ullamcorper arcu. Vestibulum mattis sollicitudin nulla et aliquam. Donec aliquam iaculis urna ac molestie. Sed quis condimentum sem, dapibus auctor arcu. Ut vel sagittis tellus.
            Ut nec felis eros. Aenean vel ante at ipsum laoreet feugiat. Nulla in aliquam lacus. Curabitur eu pellentesque mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean fermentum tempus turpis, eget eleifend ligula consequat efficitur. Suspendisse eleifend volutpat orci quis lobortis. Nam vitae sodales magna. Vivamus interdum dignissim venenatis. Vestibulum metus ipsum, iaculis non odio a, pellentesque finibus mauris. Proin ut tempor diam. Morbi sed dapibus tellus. Nullam id justo quis tellus vestibulum imperdiet id nec elit.
          </p>
          <v-text-field />
          <div class="overline mb-4">Pourquoi voter pour nous?</div>
          <p class="font-weight-light">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque lorem consectetur aliquam lobortis. Donec commodo vestibulum urna ac aliquam. In hac habitasse platea dictumst. Morbi velit libero, tempor id ante in, varius dapibus diam. Quisque nec arcu eros. Aliquam cursus nisi ex, blandit ultricies tortor luctus eget. Duis vulputate, dolor vitae ornare tincidunt, diam dui venenatis magna, in molestie urna nulla nec lorem. Donec libero ligula, elementum vel orci in, sodales finibus nisl. In elementum turpis at elit aliquam, egestas varius purus aliquam. Pellentesque ornare metus nec velit mattis mattis. In risus dui, ultrices sed neque convallis, tempor porttitor nulla. Nulla nec volutpat nulla, eget aliquam mauris.
            Proin non sollicitudin sem. In in lacus nisi. Nullam fringilla justo enim, vitae euismod tortor pretium et. Aliquam bibendum quis est vel porta. Quisque dignissim, nulla ut faucibus interdum, massa turpis ultrices ligula, quis cursus orci purus vehicula ipsum. Sed risus felis, sagittis a nunc sit amet, pellentesque pretium justo. Maecenas vitae urna tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin sed tortor vel mi condimentum ornare. Curabitur erat tortor, rhoncus non consectetur eu, blandit eu dolor. In erat sapien, malesuada at egestas sed, aliquam ut enim. Nam ut gravida ligula, id imperdiet erat.
            Integer cursus ipsum at neque sollicitudin viverra. Donec sed mi efficitur, imperdiet sapien ac, dictum eros. Sed ullamcorper augue in urna laoreet, congue ultrices nulla gravida. Morbi pellentesque semper fermentum. Ut venenatis lacus a arcu posuere, in gravida quam volutpat. Duis est ante, tempus sit amet felis eu, tempor pretium risus. Integer efficitur diam dui, non porttitor ex egestas a. Donec quis metus eu turpis commodo tincidunt. Pellentesque venenatis neque quis orci egestas, quis ullamcorper sapien suscipit. Suspendisse elementum, erat eget fermentum feugiat, purus urna interdum magna, ac rhoncus orci eros fermentum nisi. Integer sed lacus in ante scelerisque malesuada in ullamcorper arcu. Vestibulum mattis sollicitudin nulla et aliquam. Donec aliquam iaculis urna ac molestie. Sed quis condimentum sem, dapibus auctor arcu. Ut vel sagittis tellus.
            Ut nec felis eros. Aenean vel ante at ipsum laoreet feugiat. Nulla in aliquam lacus. Curabitur eu pellentesque mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean fermentum tempus turpis, eget eleifend ligula consequat efficitur. Suspendisse eleifend volutpat orci quis lobortis. Nam vitae sodales magna. Vivamus interdum dignissim venenatis. Vestibulum metus ipsum, iaculis non odio a, pellentesque finibus mauris. Proin ut tempor diam. Morbi sed dapibus tellus. Nullam id justo quis tellus vestibulum imperdiet id nec elit.
          </p>
        </v-list-item-content>
      </v-card>
    </v-container>
  </v-app>
</template>